# Generated by Django 6.0.1 on 2026-01-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=256)),
                ('author_name', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
